Nis 7283
feelitbreak/InnoClinic pull request #1
Opened 2023-08-10 14:08 UTC by feelitbreak

US-1 Sign-Up

2023-08-17 11:29 UTC, AlikseiVaniuevich commented on InnoClinic.Domain/Entities/User.cs
EmailAddress никакой нагрузки для бд не несёт. Ты его используеь для валидации?
ReenteredPassword мне кажется не нужен здесь. Это чисто фронтовая штука для валидации

2023-08-17 11:30 UTC, AlikseiVaniuevich commented on InnoClinic.Domain/Repositories/IUserRepository.cs
1. лучше использовать асинхронные методы
2. создать общий базовый репозиторий, в котором будут реализованы стандартные методы. методы унаследоваить в конкретном классе

2023-08-17 11:38 UTC, AlikseiVaniuevich requested changes

2023-08-17 11:38 UTC, AlikseiVaniuevich commented on InnoClinic.Infrastructure/ClinicDbContext.cs
дефолтное знасчение лучше пустой сторокой не делать, т.к. чаще ожидаю null. Email и Password у тебя и так обязательные поля им вообще дефолтное значение подставлять не нужно

2023-08-17 11:38 UTC, AlikseiVaniuevich commented on InnoClinic.Infrastructure/Migrations/20230810092540_RemovedUnnecessaryAttributesAndRenamedUsersTable.cs
Когда делаешь какую-то фичу, то локально можешь отменять миграции, но когда миграция уже была применена в проде, откатывать её не стоит, только в редких случая. Поэтому нужно совместить все миграции в одну

2023-08-17 11:38 UTC, AlikseiVaniuevich commented on InnoClinic.Infrastructure/Repositories/UserRepository.cs
SaveChange лучше применять, когда все затрекал в ef. Поэтому делают отдельный вызов для запуска скриптов базу. Почитай про паттерн unit of work

2023-08-17 11:38 UTC, AlikseiVaniuevich commented on InnoClinic/Controllers/AuthorizationController.cs
у тебя нарушены принципы 3-х слойной архитектуры, сразу добавляешь доступ к базе у уонтроллера. Плюс нужен отдельный класс сервис, который будет генерировать токен. Класс для генерации токена тоже нужно добавить в DI

2023-08-17 11:38 UTC, AlikseiVaniuevich commented on InnoClinic/Program.cs
Используй extension методы. Почитай про options паттерн

2023-08-17 13:29 UTC, closed without merging

2023-08-18 09:18 UTC, feelitbreak commented on InnoClinic.Domain/Entities/User.cs
EmailAddress для валидации. ReenteredPassword убрал

2023-08-18 10:51 UTC, feelitbreak commented on InnoClinic.Domain/Repositories/IUserRepository.cs
Исправил в 7284

2023-08-18 12:13 UTC, feelitbreak commented on InnoClinic.Infrastructure/Repositories/UserRepository.cs
Добавил unit of work в 7284

2023-08-18 12:14 UTC, feelitbreak commented on InnoClinic/Controllers/AuthorizationController.cs
Сделано в 7284

2023-08-19 09:36 UTC, feelitbreak commented on InnoClinic.Infrastructure/ClinicDbContext.cs
Исправил

2023-08-19 10:00 UTC, feelitbreak commented on InnoClinic.Infrastructure/Migrations/20230810092540_RemovedUnnecessaryAttributesAndRenamedUsersTable.cs
Исправил

2023-08-19 16:37 UTC, feelitbreak commented on InnoClinic/Program.cs
Исправил